### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by wuhang** [flipkart-incubator/fk-visual-search#5]
I0904 23:39:12.683835 19176 net.cpp:84] Creating Layer reshape_leq
I0904 23:39:12.683840 19176 net.cpp:406] reshape_leq <- linear_embedding_q
I0904 23:39:12.683845 19176 net.cpp:367] reshape_leq -> linear_embedding_q (in-place)
F0904 23:39:12.683863 19176 reshape_layer.cpp:10] Check failed: top[0] != bottom[0] (0x1c81b9850 vs. 0x1c81b9850) Reshape Layer does not allow in-place computation.
*** Check failure stack trace: ***
    @     0x7fc0d40b0daa  (unknown)
    @     0x7fc0d40b0ce4  (unknown)
    @     0x7fc0d40b06e6  (unknown)
    @     0x7fc0d40b3687  (unknown)
    @     0x7fc0d47be8e7  caffe::ReshapeLayer<>::LayerSetUp()
    @     0x7fc0d473ed18  caffe::Net<>::Init()
    @     0x7fc0d4740215  caffe::Net<>::Net()
    @     0x7fc0d4747dc5  caffe::Solver<>::InitTrainNet()
    @     0x7fc0d4749203  caffe::Solver<>::Init()
    @     0x7fc0d474951f  caffe::Solver<>::Solver()
    @     0x7fc0d4725191  caffe::Creator_SGDSolver<>()
    @           0x40e0dc  caffe::SolverRegistry<>::CreateSolver()
    @           0x408b68  train()
    @           0x405b13  main
    @     0x7fc0d30a8f45  (unknown)
    @           0x4063f5  (unknown)
    @              (nil)  (unknown)

Please tell me how to fix this problem?

**Comment by chahna107** [comment]
@wuhang Hey could you tell me how do you input the triplets after generating the CSV? Which path should you enter in the prototxt file?

**Comment by wuhang** [comment]
@chahna107  Thanks for reply，I made it q_train.txt q_val.txt and p_train.txt p_val.txt and n_train.txt n_val.txt Corresponds to .csv 0,1,2 lines
my q_val.txt like this:
/data/street2shop/structured_images/wtbi_bags_query_crop/4534.jpg 0
/data/street2shop/structured_images/wtbi_bags_query_crop/4534.jpg 0
/data/street2shop/structured_images/wtbi_bags_query_crop/4534.jpg 0
Is not my dataset file order wrong？

**Comment by chahna107** [comment]
Hi @wuhang, 
**Reshape Layer does not allow in-place computation** - This error is because of the same name _linear_embedding_q_ in top and bottom parameters. Rename the top parameter to something else and all the following entries thereafter. I think this should solve the error.

**Comment by wuhang** [comment]
@chahna107 Sorry, I do not understand what you mean,Can you help me fix it?

layer {
  name: "linear_embedding_q"
  type: "InnerProduct"
  bottom: "q_concat"
  top: "linear_embedding_q"
  param {
    name: "linear_embedding_w"
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    name: "linear_embedding_b"
    lr_mult: 2.0
    decay_mult: 0.0
  }
  inner_product_param {
    num_output: 4096
    weight_filler {
      type: "gaussian"
      std: 0.00499999988824
    }
    bias_filler {
      type: "constant"
      value: 0.10000000149
    }
  }
}

layer {
  name: "reshape_leq"
  type: "Reshape"
  bottom: "linear_embedding_q"
  top:"linear_embedding_q"
  reshape_param {
    shape {
      dim: 0
      dim: 0
      dim: 1
      dim: 1
    }
  }
}

layer {
  name: "linear_embedding_q_norm"
  type: "LRN"
  bottom: "linear_embedding_q"
  top: "linear_embedding_q_norm"
  lrn_param {
    local_size: 8191
    alpha: 8191.0
    beta: 0.5
  }
}

Thanks!

**Comment by chahna107** [comment]
@wuhang Here you go!

layer {
name: "reshape_leq"
type: "Reshape"     _// This reshape layer cannot have same top and bottom name_
bottom: "linear_embedding_q"
top:"**linear_embedding_q_new**"
reshape_param {
shape {
dim: 0
dim: 0
dim: 1
dim: 1
}
}
}

layer {
name: "linear_embedding_q_norm"
type: "LRN"
bottom: "**linear_embedding_q_new**"
top: "linear_embedding_q_norm"
lrn_param {
local_size: 8191
alpha: 8191.0
beta: 0.5
}
}

You might also have to change the name similarly for layers **reshape_lep** and **reshape_len**.

**Comment by wuhang** [comment]
@chahna107  Thanks It's work!
