### ISSUE TITLE
Can you give a visnet deploy file example?

### ISSUE THREAD

**Issue by wuhang** [flipkart-incubator/fk-visual-search#6]
I do not understand how to turn into the deploy file

**Comment by wuhang** [comment]
@chahna107

**Comment by chahna107** [comment]
Hey @wuhang I have never tried doing it. But I guess all you need to do is remove the loss and accuracy layers and just define a data layer with name and dimensions eliminating all the other parameters from data layer. The rest of the layers remain same.
You can look at the deploy and train prototxt files in the model samples given in Caffe (ex. Alexnet, CaffeNet etc.) for reference.
